benches/generators.rs
benches/range_proof.rs
src/extended_mask.rs
src/generators/pedersen_gens.rs
src/range_proof.rs
src/range_statement.rs
src/ristretto.rs
tests/ristretto.rs

Reword extension degree enums to better describe the extension degree and to not use an 'off by one' type logic

chore: reword extension degree enums

---

src/range_proof.rs
src/utils/generic.rs

Add methods to retrieve extension degree from a proof and a serialized proof. This will assist verifiers in ensuring that the statement contains Pedersen generators of the correct extension degree before attempting verification.

feat: add methods to retrieve extension degree

---

Cargo.toml
src/protocols/curve_point_protocol.rs

Using `curve25519-dalek = { package = "curve25519-dalek-ng", version = "4.1"`
instead of `curve25519-dalek = { package = "curve25519-dalek", version = "4.0.0-pre.2"`
due to issues with `zeroize`

chore: revert 'curve25519-dalek'

---

Cargo.toml
benches/range_proof.rs
tests/ristretto.rs

Move away for `curve25519-dalek-ng` and rather use `curve25519-dalek` as this is the more updated repo.
Updated the version as this is a breaking change with respect to dependencies. 
Matched the version of `rand` to `rand_core` so that the traits can work.

feat: port to dalek for curve

---

benches/range_proof.rs
src/range_proof.rs
tests/ristretto.rs

Splits batches during verification. Updates the API to require callers to specify a verification action.
Closes [issue #21](https://github.com/tari-project/bulletproofs-plus/issues/21).
BREAKING CHANGE: Changes the verification API.

feat!: split batches for verification

---

Cargo.toml

`merlin = "3"` uses `rand_core = "6"` instead of `rand_core = "5"` like the rest of the code base

fix: fix rand_core inequality

---

lints.toml
src/utils/generic.rs

Nonces used for mask recovery are generated using hashes of a label, seed, and two optional indexes. The label is included using the `persona` field available in `Blake2b`, and the seed is of fixed length. However, the indexes are `usize` and encoded in a manner that is platform dependent. This means that mask recovery on a platform with a different pointer size than the prover will fail to produce the correct mask.
This work updates to use a `u32` encoding, returning an error if the index exceeds this limit. This should never occur, given the typical range of indexes used. It adds tests and does some minor refactoring.
Closes [issue 30](https://github.com/tari-project/bulletproofs-plus/issues/30).
BREAKING CHANGE: Changes the way that seed nonces are used in mask recovery. Existing range …

fix!: nonce index encoding

---

Cargo.toml
benches/range_proof.rs
src/generators/bulletproof_gens.rs
src/generators/generators_chain.rs
src/generators/mod.rs
src/range_parameters.rs
src/range_proof.rs
src/range_statement.rs
src/ristretto.rs
src/traits.rs
src/transcripts.rs

Uses precomputation of fixed generator vectors to speed up verification, at the cost of storing precomputation tables between verification operations. This doesn't use precomputation on the Pedersen generators, since those can be set independently of the others, and we can't mix-and-match precomputation tables due to upstream limitations.
Note that this requires and uses a custom curve library fork. The fork supports partial precomputation by removing an existing restriction about matching the number of static points and scalars used for precomputation evaluation. It also implements `Clone` on the underlying types used for precomputation. This is unfortunate, since due to their size (several megabytes in total) such tables should almost certainly never be cloned. However, it's done for …

feat: use precomputation on (most) fixed generators

---

src/inner_product_round.rs

The inner-product protocol implementation includes many unnecessary clones when computing per-round multiscalar multiplication evaluations. These are unnecessary, since the evaluation function can accept reference iterators. Further, some multiplicative scalar offsets were being computed twice.
This PR cleans up these parts of the protocol for memory and computational efficiency, The evaluations now use only references, eliminating the clones. It's also more clever about scalar offsets to reduce duplicated computations.
Closes #33.

chore: inner-product protocol cleanup

---

src/range_proof.rs

Currently, bit vector commitments are computed using [multiscalar multiplication](https://github.com/tari-project/bulletproofs-plus/blob/cd7588ee8eaebe862fe9cf5d7c3fd92981703e87/src/range_proof.rs#L265-L273) against the inner-product generators. However, this can be simplified by using the shiny new [generator precomputation](https://github.com/tari-project/bulletproofs-plus/pull/19) feature.

feat: simplify bit vector commitment

---

.github/workflows/test.yml
Cargo.toml
benches/range_proof.rs
src/errors.rs
src/generators/bulletproof_gens.rs
src/generators/generators_chain.rs
src/inner_product_round.rs
src/protocols/scalar_protocol.rs
src/protocols/transcript_protocol.rs
src/range_parameters.rs
src/range_proof.rs
src/ristretto.rs
src/utils/generic.rs
tests/ristretto.rs

Updates the curve library and associated dependencies.
One change of note is that precomputation tables are now maintained in an `Rc` instead of an `Arc` due to trait bounds.

chore: update curve library and dependencies

---

CHANGELOG.md
Cargo.toml

Update the version
* Changes the way that seed nonces are used in mask
recovery. Existing range proofs will verify, but will fail to recover
the correct mask.
* simplify bit vector commitment ([35](https://github.com/tari-project/bulletproofs-plus/issues/35)) ([f831d64](https://github.com/tari-project/bulletproofs-plus/commit/f831d64c1bc559c1603d375eae4b2c5b438a1c8b)), closes [/github.com/tari-project/bulletproofs-plus/blob/cd7588ee8eaebe862fe9cf5d7c3fd92981703e87/src/range_proof.rs#L265-L273](https://github.com/tari-project//github.com/tari-project/bulletproofs-plus/blob/cd7588ee8eaebe862fe9cf5d7c3fd92981703e87/src/range_proof.rs/issues/L265-L273)
* use precomputation on (most) fixed generators ([19](https://github.com/tari-project/bulletproofs-plus/issues/19)) …

chore: version 0.3.0

---

Cargo.toml

Update the curve library dependency to use a crate reference for consistency.
Closes #39.

chore: use crate reference for curve library

---

src/generators/bulletproof_gens.rs
src/range_parameters.rs
src/traits.rs

Changed Precomputation `Rc` to `Arc` as `Rc<VartimeRistrettoPrecomputation>` cannot be shared between threads safely

feat: change precomputation `rc` to `arc`

---

src/range_statement.rs

Range statement initialization requires the number of minimum value promises to match the number of commitments. There's currently a logic error that renders this check incorrect.
This PR fixes the logic. A test will be included in a [broader test PR](https://github.com/tari-project/bulletproofs-plus/pull/47), but the logic change is here for scope.

fix: promise check in range statement

---

src/range_proof.rs

When computing the `d` vector, the prover and verify each allocate too much space for it. This is unnecessary, since the number of scalar elements in the vector is known.
This PR fixes the over-allocation by correcting the requested capacity. This can be checked manually by examining the number of elements pushed to the vector in both the prover and verifier cases.

fix: reduce vector capacity

---

src/commitment_opening.rs
src/extended_mask.rs
src/inner_product_round.rs
src/protocols/curve_point_protocol.rs
src/protocols/scalar_protocol.rs
src/protocols/transcript_protocol.rs
src/range_parameters.rs
src/range_proof.rs
src/range_statement.rs
src/range_witness.rs
src/utils/generic.rs

[Coverage](https://coveralls.io/github/tari-project/bulletproofs-plus?branch=main) for the repository is pretty good, but can be improved by adding tests.
This PR adds tests across the board.
There are a few notable changes made for more robust coverage that should receive extra attention:
- The looping strategy for `Scalar::random_not_zero` has been modified from a `loop` to a `while`. This imposes an extra constant-time equality check, but this is done directly on byte arrays and is very fast.
- The `TranscriptProtocol` trait function `append_scalar` was unused, so it has been removed entirely.
- The `RangeParameter` getter function `bp_gens` was unused, so it has been removed entirely.

test: improve coverage

---

src/generators/bulletproof_gens.rs
src/traits.rs

Changes the cloning strategy for `BulletproofGens` from derived to manual. This removes the need for the curve library precomputation struct to support cloning.

chore: manually clone generators

---

src/inner_product_round.rs
src/protocols/curve_point_protocol.rs

Simplifies the handling of prover inner-product generator folding for efficiency. Currently, this folding process is done using element-by-element scalar-group multiplication followed by group addition. This PR combines these operations into element-by-element multiscalar multiplications. The result is an impressive 35% speedup for single 64-bit range proving.
Also removes unnecessary helper functions.

feat: simplify inner-product generator folding

---

src/range_proof.rs

Adds a few minor optimizations to the verifier.
In the case of verification with no mask extraction, the vector used to store optional mask data is constructed empty with no capacity hint, but has `None` values pushed to it, resulting in unnecessary reallocation. This is now fixed by performing the correct allocation immediately.
A few scalar multiplications were being performed repeatedly. These are now computed only once per proof.

feat: minor verifier optimizations

---

README.md

Updates rough benchmark data against Bulletproofs. The verification number is worse than originally thought, but this is likely due to differences in the curve library version that have been [made consistent](https://github.com/tari-project/bulletproofs/pull/22).

docs: update benchmark data

---

CHANGELOG.md
Cargo.toml

* change precomputation `rc` to `arc` ([44](https://github.com/tari-project/bulletproofs-plus/issues/44)) ([d495fb2](https://github.com/tari-project/bulletproofs-plus/commit/d495fb24f9c7c34e0bfb0a38598b67e216fc56bf))
* minor verifier optimizations ([53](https://github.com/tari-project/bulletproofs-plus/issues/53)) ([7960214](https://github.com/tari-project/bulletproofs-plus/commit/796021499f3812908cfd0409951a1c944d4b71fc))
* simplify inner-product generator folding ([52](https://github.com/tari-project/bulletproofs-plus/issues/52)) ([271892c](https://github.com/tari-project/bulletproofs-plus/commit/271892c7727547da7024500e5b77a2d5894eaa3f))
* promise check in range statement ([48](https://github.com/tari-project/bulletproofs-plus/issues/48)) …

chore: bump version

---

benches/generators.rs

A comment in the generator benchmarks describes how to use all supported extension degrees, but it used an outdated `enum`. This updates the comment so it is correct.

docs: fix benchmark extension degrees

---

README.md
src/range_proof.rs

As part of proof verification, the verifier must compute the sum of consecutive nonzero powers of one of the Fiat-Shamir challenges. Currently, this is done naively by iteratively computing powers and adding them into an accumulator. Because the number of powers is equal to the product of the bit length and aggregation factor, this is nontrivial.
The computation can be made far more efficient. Because the sum of powers is a partial sum of a geometric series, it can be computed using [a well-known formula](https://mathworld.wolfram.com/GeometricSeries.html) (which is already used elsewhere in the verifier).
The change requires computation of an additional scalar inverse. As part of the optimization, all scalar inversions performed by the verifier are now included in a single batch …

feat: compute verifier challenge sum more efficiently

---

.github/workflows/test.yml

The current `nightly-2022-12-10` toolchain now breaks CI testing due to a dependency not supporting it.
This PR updates to the more recent `nightly-2023-06-04` toolchain for checks and tests.

ci: update nightly toolchain

---

src/range_proof.rs

The getter functions for the inner-product round vectors have minor issues.
First, they perform an unnecessary cloning during decompression. Second, they return a `Result` that produces an error if the vectors are empty, which cannot happen in practice. Finally, the getters for the compressed vectors are entirely unnecessary.
This PR removes the cloning, gets rid of the compressed getters, and changes the return type of the decompressed getters. It also uses iterators where appropriate.

fix: clean up getter functions and remove clones

---

lints.toml

There are currently several `clippy` [groups](https://github.com/rust-lang/rust-clippy#clippy) that are useful, but are not included in `lints.toml`. This PR adds the default `clippy::all` group to the deny list, and cleans up some individual lints that are made redundant by this change. No code changes are needed as a result of this.
Closes #76.

test: expand and clean up lints

---

src/range_proof.rs
src/utils/generic.rs

Proof serialization and deserialization currently use a custom design that optimizes space. However, the implementation relies heavily on slice indexing and is not particularly clear.
This PR updates the serialization and deserialization logic. It replaces slice indexing with chunked iteration to avoid panic conditions and improve clarity. It also modifies the serialization structure to make bounds checking more intuitive.
Closes #65.
BREAKING CHANGE: Modifies the structure of serialized proofs.

feat!: clean up serialization

---

Cargo.toml
src/range_proof.rs

This adds basic deserialization fuzz testing to CI via [`quickcheck`](https://github.com/BurntSushi/quickcheck). Because it uses a limited number of randomized test runs, it is not particularly thorough, and should not be considered a replacement for the fuzz testing added in #79. That being said, it's a reasonable sanity check and runs quickly.
Closes #80.

ci: deserialization fuzz testing

---

.github/workflows/check_licence.yml
.github/workflows/clippy-check.yml
.github/workflows/source-cov.yml
.github/workflows/test.yml

Unfortunately, the popular `actions-rs` project, which supported Rust CI, has been [unmaintained](https://github.com/actions-rs/toolchain/issues/216) for some time. In addition, the default repository `checkout` action has been [updated](https://github.com/actions/checkout/releases/tag/v4.0.0). Finally, documentation builds include dependencies, which slows down testing unnecessarily.
This PR addresses all of these issues.
First, it migrates from `actions-rs` to the [maintained](https://github.com/dtolnay/rust-toolchain) `dtolnay/rust-toolchain` action. Further, it updates the `checkout` action. Finally, it passes a [flag](https://doc.rust-lang.org/cargo/commands/cargo-doc.html#documentation-options) that ignores dependencies when building documentation. The result is a more modern and …

ci: update CI actions

---

benches/range_proof.rs
src/range_proof.rs
tests/ristretto.rs

Currently, transcript labels are assumed to be [common](https://github.com/tari-project/bulletproofs-plus/blob/d9d0cc9063f85684179908569227dda251981751/src/range_proof.rs#L432) when verifying a batch of proofs. This PR generalizes the batch verifier API to accept a vector of labels, each of which is applied to the corresponding proof.
Closes #64.
BREAKING CHANGE: Changes the batch verification API.

feat!: generalize batch transcript labels

---

Cargo.toml
src/generators/pedersen_gens.rs
src/lib.rs
src/ristretto.rs

Extended commitment generators are currently [produced](https://github.com/tari-project/bulletproofs-plus/blob/502ae9fa35a39afc5793210e4301023a7ca7ea60/src/ristretto.rs#L154-L179) using the `lazy_static` macro. Unfortunately, `lazy_static` is [no longer actively maintained](https://crates.io/crates/lazy_static). Other repositories in the ecosystem are moving to `once_cell`, which is [actively maintained](https://crates.io/crates/once_cell).
This PR migrates from `lazy_static` to `once_cell`. In the process, it cleans up the construction. Specifically, it moves from using word-based numbering (_e.g._ `ONE`, `TWO`) in hash inputs to numerals, which simplifies the design. It also adds a useful test that asserts the number of generators matches the size of `ExtensionDegree` to avoid panics. …

feat!: replace `lazy_static` with `once_cell`

---

README.md
src/commitment_opening.rs
src/extended_mask.rs
src/generators/pedersen_gens.rs
src/range_proof.rs
src/range_witness.rs
src/utils/generic.rs

Adds zeroizing and zeroing on drop to `ExtendedMask`. Moves from manual zeroizing-on-drop to the derived `ZeroizeOnDrop` trait for `CommitmentOpening` and `RangeWitness`.
Updates the prover algorithm to zeroize value- and mask-related data, including nonces.
Updates the documentation with a brief note about zeroizing support and caveats.
Closes #71.

feat: improve zeroizing support

---

src/range_proof.rs

Removes a case where a test used `panic` in favor of an `is_err()` assertion, which is more idiomatic and improves coverage.

test: remove test panic to improve coverage

---

src/range_proof.rs

Adds an extra check for unused deserialization data to ensure proof serialization is canonical. Removes redundant length checks.
Currently, serialized proof data is read as [chunks](https://github.com/tari-project/bulletproofs-plus/blob/e01c380186111c1fbe3fba213d1b492beff11b9d/src/range_proof.rs#L1017-L1020) and [tuples](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.tuples) for parsing purposes. Each of these functions can have leftover data. However, existing length checks ensure such conditions cannot occur.
This PR replaces the length checks with a final check that there is no leftover data. This helps to assert that serialization is canonical and simplifies deserialization.
Closes #82.

fix: add check for unused deserialization data

---

src/extended_mask.rs
src/generators/pedersen_gens.rs
src/range_proof.rs

Currently, `ExtensionDegree` discriminants are represented as `isize` by the compiler. The enumeration implements `TryFrom<usize>` via a wrapper to a public function `ExtensionDegreee::try_from_size` that is used in the library. This is inelegant, makes deserialization (which acts on bytes) more awkward, and introduces the possibility that a future enumeration update could overflow `u8` and cause serialization problems.
This PR moves the functionality of `ExtensionDegree::try_from_size` into a `TryFrom<u8>` implementation, and implements `TryFrom<usize>` as a wrapper. It changes the discriminant representation to `u8`, which will ensure that any future change to `ExtensionDegree` that could overflow will be caught by the compiler.
BREAKING CHANGE: Introduces a change to the …

chore!: clean up `ExtensionDegree`

---

src/range_parameters.rs

Removes public methods that became unused after #87 was merged.
BREAKING CHANGE: Removes unused methods that were public, which is technically a breaking change.

chore!: unused method cleanup

---

src/range_proof.rs

Cleans up the prover by replacing some indexing with iterator operations to address suggestions made in an audit.
Closes #88.

fix: prover cleanup

---

src/range_proof.rs

Currently, deserialization includes repeated boilerplate for parsing each proof element from a chunked iterator. This refactors the boilerplate to avoid repetition. It doesn't do the same for the tuple iterator, since that parsing logic is handled differently.

chore: refactor deserialization parsing

---

.github/workflows/test.yml
src/protocols/scalar_protocol.rs

Currently, CI testing uses a fixed nightly toolchain. While this is useful against a spurious nightly build, the repository already uses the latest nightly for formatting, lints, and checks. I think it's worth it to stick with the latest nightly across the board.
Additionally, this updates documentation checks to fail on warnings. This ensures that the documentation warnings don't go unnoticed.

ci: update nightly and fail on doc warnings

---

src/range_proof.rs

When producing a proof, the prover does not currently check that the provided witness value is within the range specified by the statement bit length. It also does not check that the witness corresponds to valid openings of the statement commitments. This is not a security issue (the verifier will reject such an invalid proof), but it means that the caller may produce an invalid proof that does not return an error.
This PR adds these checks, and ensures that the prover returns an error if they fail. It also adds unit tests exercising various failure modes.
Closes #97.

fix: improve prover consistency checks

---

src/range_proof.rs

Currently, the prover will panic if the statement aggregation factor does not precisely correspond to that of the inner-product generators. It would be best to allow the prover to use a larger generator set, similarly to how the verifier operates, in order to be more flexible. This PR adds such a fix, and includes a regression test.
Review of this PR should include asserting that removing the fix code will fail the regression test.
Closes #99.

fix: don't panic on inconsistent generators

---

.github/workflows/test.yml
Cargo.toml
README.md
benches/range_proof.rs
src/commitment_opening.rs
src/errors.rs
src/extended_mask.rs
src/generators/aggregated_gens_iter.rs
src/generators/bulletproof_gens.rs
src/generators/generators_chain.rs
src/generators/mod.rs
src/generators/pedersen_gens.rs
src/lib.rs
src/protocols/curve_point_protocol.rs
src/protocols/scalar_protocol.rs
src/protocols/transcript_protocol.rs
src/range_parameters.rs
src/range_proof.rs
src/range_statement.rs
src/range_witness.rs
src/ristretto.rs
src/utils/generic.rs
tests/ristretto.rs

This PR makes the library friendly to `no-std` environments.
It also adds a new (default) `std` feature that enables corresponding functionality in dependencies.
It updates tests and benchmarks to use a seeded `ChaCha12`-based pseudorandom number generator to ensure these don't require `std` or `rand` (which makes CI much cleaner).
Finally, it adds a `wasm32-unknown-unknown` CI build target to ensure everything works as expected in a `no-std` environment.
Supersedes #103.
Closes #102.

feat: support `no-std` environments

---

src/range_proof.rs
src/range_witness.rs
src/transcripts.rs

As noted in #108, it's possible to improve the robustness of prover nonces by using Merlin's `TranscriptRng` functionality.
This PR moves all prover nonce generation to this design. In particular, it ensures that the most up-to-date state of the transcript is used each time the prover needs secure randomness (per the Merlin [documentation](https://docs.rs/merlin/latest/merlin/struct.TranscriptRngBuilder.html#note)). The verifier also uses this to produce its random weights.
It also takes the opportunity to refactor transcript operations so they are cleaner and likely safer to use.
Closes #108.

feat: use `TranscriptRng` for random number generation

---

src/range_proof.rs
src/transcripts.rs

Recent work in #109 uses Merlin's `TranscriptRng` functionality to improve handling of random number generation, and also refactors transcript operations for safer use through a `RangeProofTranscript` wrapper.
A [suggestion](https://github.com/tari-project/bulletproofs-plus/pull/109#discussion_r1449861417) by @sdbondi recommends moving the `TranscriptRng` into `RangeProofTranscript` so the prover and verifier aren't responsible for it. This PR adds such a change.
It also updates `RangeProofTranscript` to hold a mutable reference to the external random number generator. This ensures that the prover and verifier can't accidentally use it instead of the `TranscriptRng`.

feat: move RNGs into `RangeProofTranscript`

---

.github/workflows/test.yml

This PR flips the script on #92 and pins the nightly toolchain. This is necessary due to an [upstream issue](https://github.com/dalek-cryptography/curve25519-dalek/issues/618) that now fails nightly CI.

ci: pin nightly toolchain

---

benches/range_proof.rs
src/protocols/transcript_protocol.rs
src/range_proof.rs
src/transcripts.rs
src/utils/mod.rs
src/utils/nullrng.rs
tests/ristretto.rs

The verifier currently requires support for a random number generator, either provided by the caller or taken from `OsRng`. This is only to produce weights used in the batch verification process; the weights do not need to be cryptographically secure, but must not be known to the prover. This is fine if the verifier has access to a good random number generator, but is not ideal or particularly flexible; in particular, it likely precludes having a WASM verifier.
This PR uses `TranscriptRng` functionality to produce these weights deterministically. It removes the need for the verifier to supply or support any random number generator.
We start by instantiating a new Merlin weight transcript whose only purpose is to bind all proofs together. After processing each proof's …

feat!: remove verifier RNG requirement

---

benches/range_proof.rs
clippy.toml
lints.toml
src/range_proof.rs
src/ristretto.rs
src/transcripts.rs
tests/ristretto.rs

The [Quarkslab audit](https://github.com/tari-project/bulletproofs-plus/blob/da71f7872f02a0e9d3000c316bb083181daa9942/docs/quarkslab-audit/README.md) of this library recommended the use of an arithmetic side-effect lint. This was not done at the time due to difficulty getting the lint to work with Ristretto types, which do not pose risk.
This PR adds the lint and makes necessary changes to account for it.
Closes #117.

chore: arithmetic lint

---

.github/workflows/clippy-check.yml
.github/workflows/test.yml
Cargo.toml
src/range_proof.rs

This PR moves all CI to the stable toolchain, with the single exception of formatting (which requires nightly). It does this by cleaning up the `rand` feature to use `rand_core::OsRng`, which lets the `no_std` build run properly on stable.
Unfortunately, there is no good way to do this while keeping `quickcheck` around. This was only used for very limited fuzz testing; while having any fuzz testing be part of CI is nice, its practical benefit is likely minimal. Further, its functionality is available through the non-CI fuzzer.

ci: move to stable toolchain

---

test_coverage.sh

The workflow for source coverage sets the RUST_TOOLCHAIN envar, but `test_coverage.sh` was not respecting it.
This PR changes that and brings the coverage script in line with how it's done in, e.g. tari_cypto.

fix: update source coverage script

---

src/range_proof.rs

Batch verification vectors are allocated in part using the expected aggregation factor of each statement in the batch. However, this was being done using the aggregation factors corresponding to each statement's associated generators, which may exceed the aggregation factors actually used in the statements. The result was a possible over-allocation of these vectors.
This PR changes the allocation to use the actual aggregation factors.
Closes #126.

fix: reduce verification vector allocation

---

Cargo.toml
clippy.toml
docs/quarkslab-audit/README.md
src/range_proof.rs
src/utils/generic.rs

Partial precomputation is the sole reason for maintaining a custom curve library fork, which has proven to be a headache and limits compatibility with other libraries.
This PR removes partial precomputation altogether. If you supply parameters with more inner-product generators than you need, padding is used. This incurs an efficiency hit, but only in this particular case. For the use cases in the Tari ecosystem, this is not an issue.
As a result of this change, we also switch back to the latest version of the upstream curve library and simplify some scalar exponentiation operations. The audit report is also updated to note the curve library dependency change.
Closes #128. Closes #93. Closes #96.

feat: remove partial precomputation

---

src/utils/nullrng.rs

Removes unnecessary lints that were left over from previous work.

chore: remove unnecessary lints

---

src/range_parameters.rs
src/range_proof.rs
src/range_statement.rs

The aggregation factor used in range parameters refers more specifically to the _maximum_ aggregation factor supported by the parameters. This PR does some renaming to make this more clear.
Closes #130.

chore: rename for maximum aggregation factor

---

src/range_proof.rs

This PR adds a test that the serialized element size constant is correct for Ristretto.

test: check that the serialization constant is correct

---

.github/workflows/test.yml

Splits out more CI jobs to run in parallel. This is an experiment to see if we get noticeably faster runs.

ci: run more CI in parallel

---

docs/quarkslab-audit/README.md

The QuarksLab audit report [summary](https://github.com/tari-project/bulletproofs-plus/blob/main/docs/quarkslab-audit/README.md) is out of date, since an arithmetic side-effect lint identified by the auditors is [now addressed](https://github.com/tari-project/bulletproofs-plus/pull/118).
This PR updates the documentation accordingly.

docs: update audit summary

---

src/generators/pedersen_gens.rs
src/range_proof.rs
src/utils/generic.rs

This PR removes a custom vector splitting function with [new functionality](https://doc.rust-lang.org/std/primitive.slice.html#method.split_at_checked) from the standard library. It also removes an old unused comment line that made the formatter angry.

chore: remove custom vector splitting

---

src/protocols/transcript_protocol.rs
src/range_proof.rs
src/range_statement.rs
src/ristretto.rs

The use of the `Default` implementation for Ristretto point and scalar types is somewhat non-idiomatic, since it isn't immediately clear what a "default" point or scalar must be. In practice, these are the identity group element and zero scalar, respectively.
This PR removes ambiguity and makes the library more future proof by removing all such uses. Instead, it uses the `Identity` implementation for point types and the `ZERO` constant for scalars.
Closes #141.

chore: remove use of default for points and scalars
